language: python
python:
- '2.7'
install:
- pip install -U platformio
script:
- platformio run
deploy:
  provider: releases
  api_key:
    secure: HNpp/JdVUFdFKzebHDxJMNy0K5257s28PU3toUGH+5sltYU9zsP9Fx6UAJVLJlQ89WPpW6H7iYfTmP23EJNy0A6TbmD2jh3iDA1nA+yTy5E54CzWoKl7/QgLeZd1mrw8gQvbOstzMYA+99cskOcStqXuElVY3lauZuyLCFlpkb9MzHu0WAHDtT1iDCTU7nV1Ucigx8dwR1bat6mAW47Sx7m2NvkoIgVwbZJnzSZqy9dn4TCtU1IpGTXsva4SxNy10PgGMyh53tkRxw03j+EgjdPla4zfsxiy57zDy+65Enmhj7Ho0KBZ3hRpXtu3LtMDittglCQl3V3RTIjYRiW6uGLFkSWI1QmgrsHbqrjWCV278jjm5rzi0Db+np/f9KcCgnmZvRi8V4MMpHMqLuVRwc97LKWT/n9G6x0F283bsJLWMsU2+X2mxxgtfTyXPwFsnhTW2cVA7CPifupZuY4iPjKMChQ6aNEePPz7EuliJf7plkVL2RKt0VNS2bIYrEJ6Td44AcTzRxMhJ/Qw4/7xdYxjoItvZqw+hcXDPP+81z2/csiCd3sE91ilITemturSUa+N8oiD4MEz//UJNlXZo+2ghfqWjEMCniZylVSRMNcbWlCS/DM9LF5QQPDJ5y6n89cCrusTbRLVWFX6eQj5b0bbiXVrpJMvBWKAcG5zQtg=
  file: ".pioenvs/nodemcuv2/firmware.bin"
  on:
    repo: cwi-dis/iotsaMotorServer
