# Created this action based on information found in:
# - <https://github.com/marketplace/actions/test-compile-for-arduino>
# - <https://docs.github.com/en/free-pro-team@latest/actions/quickstart>
name: build-arduino
on: 
  push:
    paths-ignore:
    - '.github/workflows/build-platformio.yml'
    - 'docs/**'
  pull_request:
  workflow_dispatch:
    inputs:
      iotsa_ref:
        description: 'iotsa branch, ref or sha'
        required: true
        default: develop
env:
  iotsa_ref: develop
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-board-fqbn:
        - esp8266:esp8266:nodemcuv2
#        - esp32:esp32:esp32thing
      
    steps:
    - name: Set iotsa_ref in environment
      run: |
        if [ "${{ github.event_name }}" == "repository_dispatch" ]; then 
            echo "iotsa_ref=${{ github.event.client_payload.iotsa_ref }}" >> $GITHUB_ENV
            echo "repository_dispatch: iotsa_ref=${{ github.event.client_payload.iotsa_ref }}"
        fi
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then 
            echo "iotsa_ref=${{ github.event.inputs.iotsa_ref }}" >> $GITHUB_ENV
            echo "workflow_dispatch: iotsa_ref=${{ github.event.inputs.iotsa_ref }}"
        fi
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install Arduino platforms and libraries
      run: |
        arduino-cli config init --overwrite
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli config add board_manager.additional_urls "https://espressif.github.io/arduino-esp32/package_esp32_index.json"
        arduino-cli config add board_manager.additional_urls "https://arduino.esp8266.com/stable/package_esp8266com_index.json"
        arduino-cli core update-index
        arduino-cli core install "esp32:esp32"
        arduino-cli core install "esp8266:esp8266"
        arduino-cli lib install "Adafruit NeoPixel"
        arduino-cli lib install "ArduinoJson"
        arduino-cli lib install "CoAP simple library"
        arduino-cli lib install "DHT sensor library"
        arduino-cli lib install "Adafruit Unified Sensor"
        arduino-cli lib install "Ds1302"
        arduino-cli lib install "ESP32Encoder"
        arduino-cli lib install --git-url https://github.com/yutter/ArduinoJWT
        arduino-cli lib install --git-url https://github.com/jackjansen/esp32_idf5_https_server
        arduino-cli lib install --git-url https://github.com/jackjansen/esp32_idf5_https_server_compat
        arduino-cli lib install --git-url https://github.com/cwi-dis/iotsa#${{ env.iotsa_ref }}
        arduino-cli lib list

    - name: Build for ${{ matrix.arduino-board-fqbn }}
      run: |
        arduino-cli compile --fqbn ${{ matrix.arduino-board-fqbn }}
  