# Created this action based on information found in:
# - <https://github.com/marketplace/actions/test-compile-for-arduino>
# - <https://docs.github.com/en/free-pro-team@latest/actions/quickstart>
name: build-arduino
on: 
  push:
    paths-ignore:
    - '.github/workflows/build-platformio.yml'
    - 'docs/**'
  pull_request:
  workflow_dispatch:
    inputs:
      iotsa_ref:
        description: 'iotsa branch, ref or sha'
        required: true
        detault: develop
env:
  iotsa_ref: develop
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-board-fqbn:
        - esp8266:esp8266:nodemcuv2
#        - esp32:esp32:esp32thing
      
    steps:
    - name: Set env
      run: |
        if [ "${{ github.event_name }}" == "repository_dispatch" ]; then 
            echo "iotsa_ref=${{ github.event.client_payload.iotsa_ref }}" >> $GITHUB_ENV
            echo "repository_dispatch: iotsa_ref=${{ github.event.client_payload.iotsa_ref }}"
        fi
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then 
            echo "iotsa_ref=${{ github.event.inputs.iotsa_ref }}" >> $GITHUB_ENV
            echo "workflow_dispatch: iotsa_ref=${{ github.event.inputs.iotsa_ref }}"
        fi
        
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install iotsa libraries
      uses: actions/checkout@v2
      with:
          repository: cwi-dis/iotsa
          path: CustomLibrary_iotsa
          ref: ${{ env.iotsa_ref }}
      
    - name: Install constom libraries
      uses: actions/checkout@v2
      with:
          repository: yutter/ArduinoJWT
          path: CustomLibrary_ArduinoJWT
      
    - name: Arduino build
      uses: ArminJo/arduino-test-compile@v3
      with:
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json,https://dl.espressif.com/dl/package_esp32_index.json
        required-libraries: Adafruit NeoPixel,Time,Timezone,ArduinoJson,CoAP simple library,ESP32_https_server,esp32_https_server_compat,DHT sensor library,Ds1302,AccelStepper
        arduino-board-fqbn: ${{ matrix. arduino-board-fqbn }}